import { fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { App } from "./App";

const auth={sessionToken:"session-safe",user:{userId:"user_1",email:"person@example.com",displayName:"Person",status:"active",createdAt:"2026-01-01",updatedAt:"2026-01-01"},session:{sessionId:"session_1",userId:"user_1",status:"active",createdAt:"2026-01-01",expiresAt:"2027-01-01",lastSeenAt:"2026-01-01"},workspace:{workspaceId:"workspace_1",ownerUserId:"user_1",name:"Person Workspace",status:"active",createdAt:"2026-01-01",updatedAt:"2026-01-01"},membership:{membershipId:"membership_1",workspaceId:"workspace_1",userId:"user_1",role:"owner",status:"active",createdAt:"2026-01-01",updatedAt:"2026-01-01"}};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
afterEach(()=>{localStorage.clear();vi.unstubAllGlobals()});
describe("authenticated Gexor app",()=>{
 it("registers and opens the durable workspace",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json(auth,201)).mockResolvedValueOnce(json({conversations:[]}));vi.stubGlobal("fetch",fetchMock);const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:"Create account"}));await user.type(screen.getByLabelText("Name"),"Person");await user.type(screen.getByLabelText("Email"),"person@example.com");await user.type(screen.getByLabelText("Password"),"LongPassword1!");const submit=screen.getByRole("button",{name:"Create workspace"}); fireEvent.submit(submit.closest("form")!);expect(await screen.findByText("What would you like to explore?")).toBeInTheDocument();expect(fetchMock.mock.calls[0][0]).toBe("/api/v1/auth/register")});
 it("restores a session after refresh",async()=>{localStorage.setItem("gexor.session","session-safe");const {sessionToken:_,...current}=auth;vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(json(current)).mockResolvedValueOnce(json({conversations:[]})));render(<App/>);expect(await screen.findByText("What would you like to explore?")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Log out"})).toBeInTheDocument()});
 it("shows safe API validation errors",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json({detail:"Check the highlighted fields.",requestId:"req",retryable:false},400)));const user=userEvent.setup();render(<App/>);await user.type(screen.getByLabelText("Email"),"person@example.com");await user.type(screen.getByLabelText("Password"),"LongPassword1!");await user.click(screen.getAllByRole("button",{name:"Log in"})[1]!);expect(await screen.findByRole("alert")).toHaveTextContent("Check the highlighted fields.")});
});
