import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { AuthenticationResponse, ConversationListResponse, ConversationMessage, ConversationMessagesResponse, ConversationSummary, CurrentUserResponse, ModelCatalogueEntry, ProviderCatalogueEntry, RuntimeExecutionResponse, WorkspaceProviderConnection } from "@gexor/contracts";
import { ApiClient, ApiError } from "./api/client";
import { sessionStorage } from "./auth/storage";

type AuthMode="login"|"register"; type View="chat"|"settings";
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export function App(){
 const [token,setToken]=useState(sessionStorage.load); const [current,setCurrent]=useState<CurrentUserResponse>(); const [booting,setBooting]=useState(Boolean(token)); const [authMode,setAuthMode]=useState<AuthMode>("login"); const [error,setError]=useState("");
 const client=useMemo(()=>new ApiClient(token,current?.workspace.workspaceId),[token,current]);
 const endSession=useCallback(()=>{sessionStorage.clear();setToken(undefined);setCurrent(undefined);setBooting(false)},[]);
 useEffect(()=>{if(!token){setBooting(false);return} new ApiClient(token).request<CurrentUserResponse>("/api/v1/auth/me").then(setCurrent).catch(endSession).finally(()=>setBooting(false))},[token,endSession]);
 async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const data=new FormData(e.currentTarget);try{const body=authMode==="register"?{displayName:String(data.get("displayName")),email:String(data.get("email")),password:String(data.get("password"))}:{email:String(data.get("email")),password:String(data.get("password"))};const result=await new ApiClient().request<AuthenticationResponse>(`/api/v1/auth/${authMode}`,{method:"POST",body:JSON.stringify(body)});sessionStorage.save(result.sessionToken);setToken(result.sessionToken);setCurrent(result)}catch(e){setError(message(e))}}
 async function logout(){try{await client.request("/api/v1/auth/logout",{method:"POST"})}finally{endSession()}}
 if(booting)return <main className="center"><div className="spinner"/><p>Restoring your workspace…</p></main>;
 if(!current)return <main className="auth-shell"><section className="brand"><span className="logo">G</span><h1>Gexor</h1><p>Your private, provider-independent AI workspace.</p></section><section className="auth-card"><div className="tabs"><button className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Log in</button><button className={authMode==="register"?"active":""} onClick={()=>setAuthMode("register")}>Create account</button></div><form onSubmit={authenticate}>{authMode==="register"&&<label>Name<input name="displayName" required minLength={2} maxLength={80} autoComplete="name"/></label>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required minLength={12} autoComplete={authMode==="login"?"current-password":"new-password"}/></label>{authMode==="register"&&<small>Use at least 12 characters. A longer passphrase is easier to remember and safer.</small>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" type="submit">{authMode==="login"?"Log in":"Create workspace"}</button></form></section></main>;
 return <Workspace current={current} client={client} logout={logout}/>;
}
function Workspace({current,client,logout}:{current:CurrentUserResponse;client:ApiClient;logout:()=>void}){const [view,setView]=useState<View>("chat");const [conversations,setConversations]=useState<ConversationSummary[]>([]);const [selected,setSelected]=useState<string>();const [messages,setMessages]=useState<ConversationMessage[]>([]);const [draft,setDraft]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const loadConversations=useCallback(async()=>{const r=await client.request<ConversationListResponse>(`/api/v1/workspaces/${current.workspace.workspaceId}/conversations`);setConversations(r.conversations);setSelected(s=>s??r.conversations[0]?.conversationId)},[client,current.workspace.workspaceId]);
 const loadMessages=useCallback(async(id:string)=>{const r=await client.request<ConversationMessagesResponse>(`/api/v1/conversations/${id}/messages`);setMessages(r.messages)},[client]);
 useEffect(()=>{loadConversations().catch(e=>setError(message(e)))},[loadConversations]);useEffect(()=>{if(selected)loadMessages(selected).catch(e=>setError(message(e)));else setMessages([])},[selected,loadMessages]);
 async function create(){const title=prompt("Conversation title",`Conversation ${conversations.length+1}`)?.trim();if(!title)return;try{const c=await client.request<ConversationSummary>(`/api/v1/workspaces/${current.workspace.workspaceId}/conversations`,{method:"POST",body:JSON.stringify({title})});await loadConversations();setSelected(c.conversationId)}catch(e){setError(message(e))}}
 async function send(e:FormEvent){e.preventDefault();const text=draft.trim();if(!text||busy)return;setBusy(true);setError("");try{let id=selected;if(!id){const c=await client.request<ConversationSummary>(`/api/v1/workspaces/${current.workspace.workspaceId}/conversations`,{method:"POST",body:JSON.stringify({title:text.slice(0,60)})});id=c.conversationId;setSelected(id)}setDraft("");const accepted=await client.request<{executionId:string}>(`/api/v1/conversations/${id}/messages`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({content:[{type:"text",text}]})});for(let i=0;i<100;i++){const ex=await client.request<RuntimeExecutionResponse>(`/api/v1/executions/${accepted.executionId}`);await loadMessages(id);if(["completed","failed","timed_out","cancelled"].includes(ex.state)){if(ex.failure)throw new ApiError(ex.failure.detail,0,ex.failure.code,ex.failure.retryable);break}await wait(500)}await loadConversations()}catch(e){setDraft(text);setError(message(e))}finally{setBusy(false)}}
 return <div className="app-shell"><header><div><span className="logo small">G</span><strong>Gexor</strong></div><nav><button className={view==="chat"?"active":""} onClick={()=>setView("chat")}>Chat</button><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}>Providers</button><button onClick={logout}>Log out</button></nav></header>{view==="settings"?<Settings client={client} workspaceId={current.workspace.workspaceId}/>:<main className="workspace"><aside><div className="aside-head"><span>Conversations</span><button onClick={create} aria-label="New conversation">＋</button></div>{conversations.length===0?<p className="muted">Start a conversation below.</p>:conversations.map(c=><button className={selected===c.conversationId?"conversation active":"conversation"} onClick={()=>setSelected(c.conversationId)} key={c.conversationId}>{c.title}</button>)}</aside><section className="chat"><div className="chat-title"><div><h1>{conversations.find(c=>c.conversationId===selected)?.title??"New conversation"}</h1><p>{current.workspace.name}</p></div><button className="mobile-new" onClick={create}>New</button></div><div className="messages">{messages.length===0?<div className="empty"><span className="logo">G</span><h2>What would you like to explore?</h2><p>Your conversation will remain in this workspace after refresh.</p></div>:messages.map(m=><article key={m.messageId} className={m.role}><span>{m.role==="user"?current.user.displayName:"Gexor"}</span><p>{m.text}</p>{m.execution&&m.execution.state!=="completed"&&<small>{m.execution.failure?.detail??`Execution: ${m.execution.state}`}</small>}</article>)}</div>{error&&<div className="error banner" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}<form className="composer" onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Message Gexor…" rows={1} maxLength={12000} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button className="send" disabled={busy||!draft.trim()}>{busy?"…":"↑"}</button></form></section></main>}</div>}
function Settings({client,workspaceId}:{client:ApiClient;workspaceId:string}){const [providers,setProviders]=useState<ProviderCatalogueEntry[]>([]);const [models,setModels]=useState<ModelCatalogueEntry[]>([]);const [connections,setConnections]=useState<WorkspaceProviderConnection[]>([]);const [error,setError]=useState("");const load=useCallback(async()=>{const [p,c]=await Promise.all([client.request<{providers:ProviderCatalogueEntry[];models:ModelCatalogueEntry[]}>("/api/v1/providers"),client.request<{connections:WorkspaceProviderConnection[]}>(`/api/v1/workspaces/${workspaceId}/provider-connections`)]);setProviders(p.providers);setModels(p.models);setConnections(c.connections)},[client,workspaceId]);useEffect(()=>{load().catch(e=>setError(message(e)))},[load]);async function connect(providerKey:string){try{const c=await client.request<WorkspaceProviderConnection>(`/api/v1/workspaces/${workspaceId}/provider-connections`,{method:"POST",body:JSON.stringify({providerKey,credentialReference:"local-env:configured"})});await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${c.connectionId}/test`,{method:"POST"});const model=models.find(m=>m.providerKey===providerKey);if(model)await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${c.connectionId}/select`,{method:"POST",body:JSON.stringify({modelKey:model.modelKey})});await load()}catch(e){setError(message(e))}}return <main className="settings"><h1>Provider connections</h1><p>Choose the model used for this workspace. Credentials stay on the API server and are never sent to this browser.</p>{error&&<p className="error">{error}</p>}<div className="provider-grid">{providers.map(p=>{const c=connections.find(c=>c.providerKey===p.providerKey&&c.status==="active");return <section className="provider-card" key={p.providerKey}><h2>{p.displayName}</h2><p>{models.filter(m=>m.providerKey===p.providerKey).map(m=>m.displayName).join(", ")}</p><span className={c?"status good":"status"}>{c?"Connected":"Not connected"}</span><button className="primary" disabled={Boolean(c)} onClick={()=>connect(p.providerKey)}>{c?"Ready":"Use server configuration"}</button></section>})}</div></main>}
function message(e:unknown){return e instanceof Error?e.message:"Something went wrong. Please try again."}
