import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, it, vi } from "vitest";
import { App } from "./App";

const current={user:{userId:"u",email:"u@example.com",displayName:"User",status:"active",createdAt:"x",updatedAt:"x"},session:{sessionId:"s",userId:"u",status:"active",createdAt:"x",expiresAt:"y",lastSeenAt:"x"},workspace:{workspaceId:"workspace_1",ownerUserId:"u",name:"My Workspace",status:"active",createdAt:"x",updatedAt:"x"},membership:{membershipId:"m",workspaceId:"workspace_1",userId:"u",role:"owner",status:"active",createdAt:"x",updatedAt:"x"}};
const conversation={conversationId:"conversation_1",workspaceId:"workspace_1",title:"Hello",status:"active",version:1,createdAt:"x",updatedAt:"x"};
const accepted={messageId:"message_1",executionId:"execution_1",state:"accepted",requestId:"r",createdAt:"x",links:{execution:"/api/v1/executions/execution_1"}};
const messages={messages:[{messageId:"message_1",conversationId:"conversation_1",role:"user",text:"Hello",state:"complete",createdAt:"x"},{messageId:"message_1:assistant",conversationId:"conversation_1",role:"assistant",text:"Canonical reply",state:"complete",createdAt:"y",execution:{executionId:"execution_1",messageId:"message_1",conversationId:"conversation_1",requestId:"r",workspaceId:"workspace_1",requestedBy:"u",state:"completed",createdAt:"x",updatedAt:"y",response:{text:"Canonical reply"},links:{self:"/api/v1/executions/execution_1"}}}]};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
function sse(){const encoder=new TextEncoder();const event1={eventId:"event_1",executionId:"execution_1",eventType:"response.delta",timestamp:"x",sequence:1,payload:{delta:"Canonical reply"}};const event2={eventId:"event_2",executionId:"execution_1",eventType:"response.completed",timestamp:"y",sequence:2,payload:{state:"completed",response:{text:"Canonical reply"}}};return new Response(new ReadableStream({start(controller){controller.enqueue(encoder.encode(`id: event_1\nevent: response.delta\ndata: ${JSON.stringify(event1)}\n\nid: event_2\nevent: response.completed\ndata: ${JSON.stringify(event2)}\n\n`));controller.close();}}),{status:200,headers:{"Content-Type":"text/event-stream"}})}
afterEach(()=>{localStorage.clear();sessionStorage.clear();vi.unstubAllGlobals()});
it("uses canonical cookie-authenticated conversation, execution, and SSE routes",async()=>{let posted=false;const fetchMock=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);const method=init?.method?.toUpperCase()??"GET";if(url==="/api/v1/auth/me")return json(current);if(url.includes("/conversations")&&method==="GET"&&!url.includes("messages")&&!url.includes("files"))return json({conversations:posted?[conversation]:[]});if(url.endsWith("/files"))return json({files:[]});if(url.endsWith("/messages")&&method==="GET")return json(posted?messages:{messages:[]});if(url.includes("/workspaces/workspace_1/conversations")&&method==="POST")return json(conversation,201);if(url.endsWith("/messages")&&method==="POST"){posted=true;return json(accepted,202)}if(url.includes("/api/v1/executions/execution_1/events"))return sse();return json({detail:`Unexpected ${method} ${url}`,requestId:"req",retryable:false},500)});vi.stubGlobal("fetch",fetchMock);const user=userEvent.setup();render(<App/>);const box=await screen.findByPlaceholderText("Message Gexor…");await user.type(box,"Hello");await user.keyboard("{Enter}");expect(await screen.findByText("Canonical reply")).toBeInTheDocument();expect(fetchMock.mock.calls.some(c=>String(c[0]).includes("/api/v1/conversations/conversation_1/messages"))).toBe(true);expect(fetchMock.mock.calls.some(c=>String(c[0]).includes("/api/v1/executions/execution_1/events"))).toBe(true);expect(fetchMock.mock.calls.every(c=>!(c[1]?.headers as Record<string,string>|undefined)?.Authorization)).toBe(true)});
