import { useCallback, useEffect, useMemo, useState } from "react";
import type { ModelCatalogueEntry, ProviderCatalogueEntry, ProviderRoutingStatus, WorkspaceProviderConnection, WorkspaceProviderConnectionsResponse, WorkspaceProviderSelection } from "@gexor/contracts";
import { ApiClient } from "./api/client";

export function ProviderSettings({client,workspaceId}:{client:ApiClient;workspaceId:string}){
  const [providers,setProviders]=useState<ProviderCatalogueEntry[]>([]);const [models,setModels]=useState<ModelCatalogueEntry[]>([]);
  const [connections,setConnections]=useState<WorkspaceProviderConnection[]>([]);const [routing,setRouting]=useState<ProviderRoutingStatus[]>([]);const [selected,setSelected]=useState<WorkspaceProviderSelection>();const [modelSelections,setModelSelections]=useState<Record<string,string>>({});const [error,setError]=useState("");
  const load=useCallback(async()=>{const [catalogue,configured]=await Promise.all([client.request<{providers:ProviderCatalogueEntry[];models:ModelCatalogueEntry[]}>("/api/v1/providers"),client.request<WorkspaceProviderConnectionsResponse>(`/api/v1/workspaces/${workspaceId}/provider-connections`)]);setProviders(catalogue.providers);setModels(catalogue.models);setConnections(configured.connections);setRouting(configured.routing);setSelected(configured.selected);setModelSelections((current)=>seedModelSelections(current,catalogue.models,configured.routing,configured.selected));},[client,workspaceId]);
  useEffect(()=>{void load().catch(value=>setError(value instanceof Error?value.message:"Provider settings could not be loaded."))},[load]);
  async function connect(providerKey:string){try{setError("");const connection=await client.request<WorkspaceProviderConnection>(`/api/v1/workspaces/${workspaceId}/provider-connections`,{method:"POST",body:JSON.stringify({providerKey,credentialReference:"local-env:configured"})});await check(connection.connectionId);const model=modelForProvider(providerKey,models,modelSelections[providerKey]);if(model)await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${connection.connectionId}/select`,{method:"POST",body:JSON.stringify({modelKey:model.modelKey})});await load()}catch(value){setError(value instanceof Error?value.message:"Provider connection failed.")}}
  async function check(connectionId:string){await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${connectionId}/test`,{method:"POST"});await load()}
  async function configure(connectionId:string,input:{enabled?:boolean;isDefault?:boolean;priority?:number;modelKey?:string}){try{setError("");await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${connectionId}/routing`,{method:"PATCH",body:JSON.stringify(input)});await load()}catch(value){setError(value instanceof Error?value.message:"Routing update failed.")}}
  const activeModelsByProvider=useMemo(()=>new Map(providers.map(provider=>[provider.providerKey,models.filter(model=>model.providerKey===provider.providerKey&&model.status==="active")])),[models,providers]);
  return <main className="settings"><h1>Provider connections</h1><p>Health checks and deterministic priority control bounded fallback. Credentials remain on the API server and never appear in this browser.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="provider-grid">{providers.map(provider=>{const connection=connections.find(item=>item.providerKey===provider.providerKey&&item.status!=="revoked");const route=connection?routing.find(item=>item.connectionId===connection.connectionId):undefined;const providerModels=activeModelsByProvider.get(provider.providerKey)??[];const chosenModelKey=modelSelections[provider.providerKey]??"";const selectedModel=selected&&connection?.connectionId===selected.connectionId?models.find(item=>item.modelKey===selected.modelKey):undefined;const ready=Boolean(connection?.status==="active"&&route?.enabled&&route.isDefault&&selectedModel&&["unknown","healthy","degraded"].includes(route.healthState));return <section className="provider-card" key={provider.providerKey}><h2>{provider.displayName}</h2><p>{models.filter(item=>item.providerKey===provider.providerKey).map(item=>`${item.displayName} (${item.status})`).join(", ")}</p><span className={route?.healthState==="healthy"?"status good":"status"}>Health: {route?.healthState??connection?.status??"not connected"}</span>{connection?<><p>Enabled: {route?.enabled?"yes":"no"}</p><p>Default: {route?.isDefault?"yes":"no"}</p><p>Selected model: {selectedModel?.displayName??route?.modelKey??"none"}</p><p>Ready: {ready?"yes":"no"}</p>{providerModels.length>1&&<label>Model<select value={chosenModelKey} onChange={(event)=>setModelSelections(value=>({...value,[provider.providerKey]:event.target.value}))}>{providerModels.map(model=><option key={model.modelKey} value={model.modelKey}>{model.displayName}</option>)}</select></label>}{providerModels.length===1&&<p>Model choice: {providerModels[0]?.displayName}</p>}<button onClick={()=>void check(connection.connectionId)}>Check health</button><button onClick={()=>void configure(connection.connectionId,{enabled:!route?.enabled})}>{route?.enabled?"Disable":"Enable"}</button><button onClick={()=>void configure(connection.connectionId,{isDefault:true,modelKey:chosenModelKey||providerModels[0]?.modelKey})} disabled={providerModels.length!==1&&!chosenModelKey}>Make default</button></>:<button className="primary" onClick={()=>void connect(provider.providerKey)}>Use server configuration</button>}</section>})}</div></main>;
}

function seedModelSelections(current:Record<string,string>,models:ModelCatalogueEntry[],routing:ProviderRoutingStatus[],selected?:WorkspaceProviderSelection):Record<string,string>{const next={...current};for(const model of models){if(model.status!=="active")continue;const route=routing.find(item=>item.modelKey===model.modelKey);if(route)next[model.providerKey]=model.modelKey;}if(selected){const model=models.find(item=>item.modelKey===selected.modelKey);if(model)next[model.providerKey]=model.modelKey;}for(const providerKey of new Set(models.map(model=>model.providerKey))){const active=models.filter(model=>model.providerKey===providerKey&&model.status==="active");if(!next[providerKey]&&active.length===1)next[providerKey]=active[0]!.modelKey;}return next;}
function modelForProvider(providerKey:string,models:ModelCatalogueEntry[],requested?:string):ModelCatalogueEntry|undefined{if(requested){const model=models.find(item=>item.modelKey===requested&&item.providerKey===providerKey&&item.status==="active");if(model)return model;}const active=models.filter(item=>item.providerKey===providerKey&&item.status==="active");return active.length===1?active[0]:undefined;}
