import { useCallback, useEffect, useState } from "react";
import type { ModelCatalogueEntry, ProviderCatalogueEntry, ProviderRoutingStatus, WorkspaceProviderConnection } from "@gexor/contracts";
import { ApiClient } from "./api/client";

export function ProviderSettings({client,workspaceId}:{client:ApiClient;workspaceId:string}){
  const [providers,setProviders]=useState<ProviderCatalogueEntry[]>([]);const [models,setModels]=useState<ModelCatalogueEntry[]>([]);
  const [connections,setConnections]=useState<WorkspaceProviderConnection[]>([]);const [routing,setRouting]=useState<ProviderRoutingStatus[]>([]);const [error,setError]=useState("");
  const load=useCallback(async()=>{const [catalogue,configured]=await Promise.all([client.request<{providers:ProviderCatalogueEntry[];models:ModelCatalogueEntry[]}>("/api/v1/providers"),client.request<{connections:WorkspaceProviderConnection[];routing:ProviderRoutingStatus[]}>(`/api/v1/workspaces/${workspaceId}/provider-connections`)]);setProviders(catalogue.providers);setModels(catalogue.models);setConnections(configured.connections);setRouting(configured.routing)},[client,workspaceId]);
  useEffect(()=>{void load().catch(value=>setError(value instanceof Error?value.message:"Provider settings could not be loaded."))},[load]);
  async function connect(providerKey:string){try{const connection=await client.request<WorkspaceProviderConnection>(`/api/v1/workspaces/${workspaceId}/provider-connections`,{method:"POST",body:JSON.stringify({providerKey,credentialReference:"local-env:configured"})});await check(connection.connectionId);const model=models.find(item=>item.providerKey===providerKey);if(model)await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${connection.connectionId}/select`,{method:"POST",body:JSON.stringify({modelKey:model.modelKey})});await load()}catch(value){setError(value instanceof Error?value.message:"Provider connection failed.")}}
  async function check(connectionId:string){await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${connectionId}/test`,{method:"POST"});await load()}
  async function configure(connectionId:string,input:{enabled?:boolean;isDefault?:boolean;priority?:number}){try{await client.request(`/api/v1/workspaces/${workspaceId}/provider-connections/${connectionId}/routing`,{method:"PATCH",body:JSON.stringify(input)});await load()}catch(value){setError(value instanceof Error?value.message:"Routing update failed.")}}
  return <main className="settings"><h1>Provider connections</h1><p>Health checks and deterministic priority control bounded fallback. Credentials remain on the API server and never appear in this browser.</p>{error&&<p className="error">{error}</p>}<div className="provider-grid">{providers.map(provider=>{const connection=connections.find(item=>item.providerKey===provider.providerKey&&item.status!=="revoked");const route=connection?routing.find(item=>item.connectionId===connection.connectionId):undefined;return <section className="provider-card" key={provider.providerKey}><h2>{provider.displayName}</h2><p>{models.filter(item=>item.providerKey===provider.providerKey).map(item=>item.displayName).join(", ")}</p><span className={route?.healthState==="healthy"?"status good":"status"}>{route?.healthState??connection?.status??"not connected"}</span>{connection?<><p>Priority {route?.priority??100}{route?.isDefault?" · default":""}</p><button onClick={()=>void check(connection.connectionId)}>Check health</button><button onClick={()=>void configure(connection.connectionId,{enabled:!route?.enabled})}>{route?.enabled?"Disable":"Enable"}</button><button onClick={()=>void configure(connection.connectionId,{isDefault:true})}>Make default</button></>:<button className="primary" onClick={()=>void connect(provider.providerKey)}>Use server configuration</button>}</section>})}</div></main>;
}
